site_name: AI Image Restoration
site_description: Documentation for the AI Image Restoration project
site_author: Siva subramani
site_url: https://restore-img.netlify.app/

theme:
  name: material
  palette:
    primary: indigo
    accent: amber
  features:
    - content.code.copy
    - content.tabs

nav:
  - Home: index.md
  - Usage: usage.md
  - Deployment: deployment.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
