[build]
  base="/"
  command = "pip install -r requirements.txt"
  publish = "templates"  # Adjust to your output folder
[build.environment]
  PIP_VERBOSE="1"
  PYTHON_VERSION="3.11"

[functions]
  directory = "functions"
